name:                mon
version:             0.1.0.0
description:         Monitoring at Serokell
github:              "serokell/mon"
license:             MPL-2.0
author:              "Serokell"
maintainer:          "hi@serokell.io"
copyright:           "2018 Serokell"

extra-source-files:
  - README.md


default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - universum

library:
  source-dirs: src
  dependencies:
    - attoparsec
    - bytestring
    - network
    - text
    - random


executables:
  local-server:
    source-dirs: server
    main: Main.hs
    dependencies:
      - mon
      - containers
      - ekg-core
      - ekg-wai
      - network
      - optparse-applicative
      - text

  client-usage-example:
    source-dirs: client-usage-example
    main: Main.hs
    dependencies:
      - mon
      - optparse-applicative
